<?php
if (!defined("ABSPATH")) { return; }

/*
* Auto-generated by Nexter Code Snippets.
* DO NOT EDIT THIS FILE MANUALLY.
*/
return array (
  'publish' => 
  array (
    '2-disable-emojis-for-faster.php' => 
    array (
      'name' => 'Disable Emojis for Faster Loading',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Performance',
        1 => 'Optimization',
        2 => 'Frontend',
      ),
      'description' => 'Disable WordPress emoji scripts to improve page speed.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-06-16 18:52:57',
      'created_at' => '2026-06-16 18:52:57',
      'file_name' => '2-disable-emojis-for-faster.php',
    ),
    '3-add-google-analytics-tracking.php' => 
    array (
      'name' => 'Add Google Analytics Tracking Code',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Analytics',
        1 => 'Tracking',
        2 => 'Frontend',
      ),
      'description' => 'Insert Google Analytics script directly without extra plugins.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-06-16 18:52:57',
      'created_at' => '2026-06-16 18:52:57',
      'file_name' => '3-add-google-analytics-tracking.php',
    ),
    '4-limit-post-revisions-to.php' => 
    array (
      'name' => 'Limit Post Revisions to Optimize Database',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Database',
        1 => 'Optimization',
        2 => 'Performance',
      ),
      'description' => 'Restrict number of saved post revisions to reduce database size.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'global',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-06-16 18:52:57',
      'created_at' => '2026-06-16 18:52:57',
      'file_name' => '4-limit-post-revisions-to.php',
    ),
    '5-customize-login-logo-link.php' => 
    array (
      'name' => 'Customize Login Logo Link URL',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Branding',
        1 => 'Login-Page',
        2 => 'Frontend',
      ),
      'description' => 'Change WordPress login logo URL to your site homepage.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-06-16 18:52:57',
      'created_at' => '2026-06-16 18:52:57',
      'file_name' => '5-customize-login-logo-link.php',
    ),
    '6-disable-gutenberg-editor-use.php' => 
    array (
      'name' => 'Disable Gutenberg Editor (Use Classic Editor)',
      'status' => 'publish',
      'tags' => 
      array (
        0 => 'Editor',
        1 => 'Backend',
        2 => 'Classic',
      ),
      'description' => 'Disable Gutenberg block editor and enable classic editor experience.',
      'type' => 'php',
      'condition' => 
      array (
        'status' => 0,
        'priority' => 10,
        'code-execute' => 'front-end',
        'php-hidden-execute' => 'yes',
      ),
      'updated_at' => '2026-06-16 18:52:57',
      'created_at' => '2026-06-16 18:52:57',
      'file_name' => '6-disable-gutenberg-editor-use.php',
    ),
  ),
  'draft' => 
  array (
  ),
  'meta' => 
  array (
    'secret_key' => 'f1f06e3ae1e229c9b2b03f69bd2e797d',
    'now_date' => '2026-07-24 12:52:23',
    'version' => '4.6.12',
    'domain' => 'http://localhost:8080',
  ),
  'error_files' => 
  array (
  ),
);