<?php
/**
 * Villa Azur — i18n layer for the reservation engine + its emails.
 *
 * Polylang translates page/post content, but it has no reach into hardcoded
 * PHP strings (labels, validation messages, email copy) generated by the
 * reservation module — that's what this file is for. Kept separate from
 * villa-azur-reservation.php so the pricing engine stays focused on pricing.
 *
 * Language for a given request is resolved in two different contexts:
 *   - Page render (popup UI text): pll_current_language() is accurate, since
 *     Polylang has already parsed the /en/, /de/... URL prefix.
 *   - Form submission (AJAX, for the authoritative email/entry text): the
 *     request goes through admin-ajax.php / REST, which carries no language
 *     prefix, so pll_current_language() cannot be trusted there. Instead the
 *     guest's language is captured into a hidden `vaz_lang` field (JS, at
 *     popup-open time, from the same CFG.lang the page was rendered with)
 *     and read back from the raw POST — the same technique villa-azur-fix.php
 *     already uses for the vaz_hp/vaz_ts spam-guard fields.
 */

if (!defined('ABSPATH')) {
    exit;
}

final class VAZ_I18N {

    const LANGS = ['fr', 'en', 'de', 'pl', 'ru'];
    const DEFAULT_LANG = 'fr';

    /** Resolve the language to use for the CURRENT request. */
    public static function current() {
        // Submission context: trust the guest-captured hidden field first.
        // phpcs:ignore WordPress.Security.NonceVerification.Missing -- FF verifies its own nonce upstream before these filters run.
        $raw = isset($_POST['data']) ? wp_unslash($_POST['data']) : '';
        if ($raw !== '') {
            parse_str($raw, $fields);
            if (!empty($fields['vaz_lang']) && in_array($fields['vaz_lang'], self::LANGS, true)) {
                return $fields['vaz_lang'];
            }
        }
        if (function_exists('pll_current_language')) {
            $lang = pll_current_language();
            if (in_array($lang, self::LANGS, true)) {
                return $lang;
            }
        }
        return self::DEFAULT_LANG;
    }

    /** Human-readable language name, in ITS OWN language (for a language picker). */
    public static function native_name($lang) {
        $names = [
            'fr' => 'Français', 'en' => 'English', 'de' => 'Deutsch',
            'pl' => 'Polski', 'ru' => 'Русский',
        ];
        return $names[$lang] ?? $lang;
    }

    /**
     * Slavic-aware pluralisation. $forms is either [one, other] (fr/en/de) or
     * [one, few, many] (pl/ru, standard mod10/mod100 CLDR-style rule).
     */
    public static function plural($lang, $n, array $forms) {
        $n = abs((int) $n);
        if (in_array($lang, ['pl', 'ru'], true) && count($forms) === 3) {
            $mod10  = $n % 10;
            $mod100 = $n % 100;
            if ($mod10 === 1 && $mod100 !== 11) {
                return $forms[0];
            }
            if ($mod10 >= 2 && $mod10 <= 4 && !($mod100 >= 12 && $mod100 <= 14)) {
                return $forms[1];
            }
            return $forms[2];
        }
        return $n === 1 ? $forms[0] : end($forms);
    }

    /** Word forms for countable nouns used across UI/emails. */
    const WORDS = [
        'night'  => ['fr' => ['nuit', 'nuits'], 'en' => ['night', 'nights'], 'de' => ['Nacht', 'Nächte'], 'pl' => ['noc', 'noce', 'nocy'], 'ru' => ['ночь', 'ночи', 'ночей']],
        'room'   => ['fr' => ['chambre', 'chambres'], 'en' => ['room', 'rooms'], 'de' => ['Zimmer', 'Zimmer'], 'pl' => ['pokój', 'pokoje', 'pokoi'], 'ru' => ['номер', 'номера', 'номеров']],
        'adult'  => ['fr' => ['adulte', 'adultes'], 'en' => ['adult', 'adults'], 'de' => ['Erwachsener', 'Erwachsene'], 'pl' => ['dorosły', 'dorosłych', 'dorosłych'], 'ru' => ['взрослый', 'взрослых', 'взрослых']],
        'child'  => ['fr' => ['enfant', 'enfants'], 'en' => ['child', 'children'], 'de' => ['Kind', 'Kinder'], 'pl' => ['dziecko', 'dzieci', 'dzieci'], 'ru' => ['ребёнок', 'ребёнка', 'детей']],
        'person' => ['fr' => ['personne', 'personnes'], 'en' => ['person', 'people'], 'de' => ['Person', 'Personen'], 'pl' => ['osoba', 'osoby', 'osób'], 'ru' => ['человек', 'человека', 'человек']],
    ];

    public static function word($lang, $key, $n) {
        $forms = self::WORDS[$key][$lang] ?? self::WORDS[$key][self::DEFAULT_LANG];
        return self::plural($lang, $n, $forms);
    }

    /** Month names, genitive case where the language requires it for "10 <month> 2026". */
    const MONTHS = [
        'fr' => [1 => 'janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'],
        'en' => [1 => 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        'de' => [1 => 'Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
        'pl' => [1 => 'stycznia', 'lutego', 'marca', 'kwietnia', 'maja', 'czerwca', 'lipca', 'sierpnia', 'września', 'października', 'listopada', 'grudnia'],
        'ru' => [1 => 'января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
    ];

    /** "10 August 2026" / "10. August 2026" (German gets the trailing period on the day). */
    public static function format_date($iso, $lang) {
        $dt = DateTime::createFromFormat('Y-m-d', $iso);
        if (!$dt) {
            return $iso;
        }
        $day   = (int) $dt->format('j');
        $month = self::MONTHS[$lang][(int) $dt->format('n')] ?? self::MONTHS[self::DEFAULT_LANG][(int) $dt->format('n')];
        $year  = $dt->format('Y');
        $dayStr = ($lang === 'de') ? $day . '.' : (string) $day;
        return "$dayStr $month $year";
    }

    /** Flatpickr-shaped calendar locale (weekday/month names, first-day-of-week, misc strings). */
    public static function calendar($lang) {
        $calendars = [
            'fr' => [
                'weekdays' => ['shorthand' => ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'], 'longhand' => ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi']],
                'months'   => ['shorthand' => ['Janv', 'Févr', 'Mars', 'Avr', 'Mai', 'Juin', 'Juil', 'Août', 'Sept', 'Oct', 'Nov', 'Déc'], 'longhand' => ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre']],
                'firstDayOfWeek' => 1, 'weekAbbreviation' => 'Sem.', 'rangeSeparator' => ' au ',
                'scrollTitle' => 'Défiler pour augmenter la valeur', 'toggleTitle' => 'Cliquer pour basculer',
                'locale' => 'fr-FR',
            ],
            'en' => [
                'weekdays' => ['shorthand' => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], 'longhand' => ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']],
                'months'   => ['shorthand' => ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], 'longhand' => ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']],
                'firstDayOfWeek' => 1, 'weekAbbreviation' => 'Wk', 'rangeSeparator' => ' to ',
                'scrollTitle' => 'Scroll to increase', 'toggleTitle' => 'Click to toggle',
                'locale' => 'en-GB',
            ],
            'de' => [
                'weekdays' => ['shorthand' => ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'], 'longhand' => ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag']],
                'months'   => ['shorthand' => ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'], 'longhand' => ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']],
                'firstDayOfWeek' => 1, 'weekAbbreviation' => 'KW', 'rangeSeparator' => ' bis ',
                'scrollTitle' => 'Scrollen zum Erhöhen', 'toggleTitle' => 'Zum Umschalten klicken',
                'locale' => 'de-DE',
            ],
            'pl' => [
                'weekdays' => ['shorthand' => ['Nd', 'Pn', 'Wt', 'Śr', 'Cz', 'Pt', 'Sb'], 'longhand' => ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota']],
                'months'   => ['shorthand' => ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'], 'longhand' => ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień']],
                'firstDayOfWeek' => 1, 'weekAbbreviation' => 'Tydz.', 'rangeSeparator' => ' do ',
                'scrollTitle' => 'Przewiń, aby zwiększyć', 'toggleTitle' => 'Kliknij, aby przełączyć',
                'locale' => 'pl-PL',
            ],
            'ru' => [
                'weekdays' => ['shorthand' => ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'], 'longhand' => ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота']],
                'months'   => ['shorthand' => ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'], 'longhand' => ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']],
                'firstDayOfWeek' => 1, 'weekAbbreviation' => 'Нед.', 'rangeSeparator' => ' по ',
                'scrollTitle' => 'Прокрутите для изменения', 'toggleTitle' => 'Нажмите для переключения',
                'locale' => 'ru-RU',
            ],
        ];
        return $calendars[$lang] ?? $calendars[self::DEFAULT_LANG];
    }

    /** Everything else: flat dotted-key lookup with fallback to French. */
    public static function t($lang, $key) {
        $table = self::table();
        return $table[$key][$lang] ?? $table[$key][self::DEFAULT_LANG] ?? $key;
    }

    private static function table() {
        static $t = null;
        if ($t !== null) {
            return $t;
        }

        $t = [
            // ── UI (popup form) ──────────────────────────────────────────────
            'ui.addRoom'       => ['fr' => 'Ajouter une chambre', 'en' => 'Add a room', 'de' => 'Zimmer hinzufügen', 'pl' => 'Dodaj pokój', 'ru' => 'Добавить номер'],
            'ui.removeRoom'    => ['fr' => 'Retirer', 'en' => 'Remove', 'de' => 'Entfernen', 'pl' => 'Usuń', 'ru' => 'Удалить'],
            'ui.room'          => ['fr' => 'Chambre', 'en' => 'Room', 'de' => 'Zimmer', 'pl' => 'Pokój', 'ru' => 'Номер'],
            'ui.roomType'      => ['fr' => 'Type de chambre', 'en' => 'Room type', 'de' => 'Zimmertyp', 'pl' => 'Typ pokoju', 'ru' => 'Тип номера'],
            'ui.board'         => ['fr' => 'Formule', 'en' => 'Meal plan', 'de' => 'Verpflegung', 'pl' => 'Wyżywienie', 'ru' => 'Питание'],
            'ui.adults'        => ['fr' => 'Adultes', 'en' => 'Adults', 'de' => 'Erwachsene', 'pl' => 'Dorośli', 'ru' => 'Взрослые'],
            'ui.children'      => ['fr' => 'Enfants (-12 ans)', 'en' => 'Children (under 12)', 'de' => 'Kinder (unter 12)', 'pl' => 'Dzieci (do 12 lat)', 'ru' => 'Дети (до 12 лет)'],
            'ui.occHintSimple' => ['fr' => 'Chambre simple : 1 personne, non cumulable.', 'en' => 'Single room: 1 person, no additions.', 'de' => 'Einzelzimmer: 1 Person, keine Zusatzbelegung.', 'pl' => 'Pokój jednoosobowy: 1 osoba, bez możliwości dostawki.', 'ru' => 'Одноместный номер: 1 человек, без доп. размещения.'],
            'ui.occHintDouble' => ['fr' => 'Chambre double : 2 adultes + 1 enfant, ou 3 adultes (3 personnes max).', 'en' => 'Double room: 2 adults + 1 child, or 3 adults (3 people max).', 'de' => 'Doppelzimmer: 2 Erwachsene + 1 Kind, oder 3 Erwachsene (max. 3 Personen).', 'pl' => 'Pokój dwuosobowy: 2 dorosłych + 1 dziecko, lub 3 dorosłych (maks. 3 osoby).', 'ru' => 'Двухместный номер: 2 взрослых + 1 ребёнок, или 3 взрослых (макс. 3 человека).'],
            'ui.summaryTitle'  => ['fr' => 'Votre estimation', 'en' => 'Your estimate', 'de' => 'Ihre Kostenschätzung', 'pl' => 'Twoja wycena', 'ru' => 'Ваш расчёт стоимости'],
            'ui.accommodation' => ['fr' => 'Hébergement', 'en' => 'Accommodation', 'de' => 'Unterkunft', 'pl' => 'Zakwaterowanie', 'ru' => 'Проживание'],
            'ui.childDiscount' => ['fr' => 'Réduction enfant (-12 ans)', 'en' => 'Child discount (under 12)', 'de' => 'Kinderermäßigung (unter 12)', 'pl' => 'Zniżka dla dziecka (do 12 lat)', 'ru' => 'Скидка для ребёнка (до 12 лет)'],
            'ui.adultDiscount' => ['fr' => '3ᵉ adulte', 'en' => '3rd adult', 'de' => '3. Erwachsener', 'pl' => '3. dorosły', 'ru' => '3-й взрослый'],
            'ui.singleSupp'    => ['fr' => 'Supplément single', 'en' => 'Single occupancy supplement', 'de' => 'Einzelzimmerzuschlag', 'pl' => 'Dopłata za pokój jednoosobowy', 'ru' => 'Доплата за одноместное размещение'],
            'ui.touristTax'    => ['fr' => 'Taxe de séjour', 'en' => 'Tourist tax', 'de' => 'Kurtaxe', 'pl' => 'Opłata turystyczna', 'ru' => 'Туристический сбор'],
            'ui.total'         => ['fr' => 'Total estimé', 'en' => 'Estimated total', 'de' => 'Geschätzter Gesamtpreis', 'pl' => 'Szacowana suma', 'ru' => 'Итого (расчётно)'],
            'ui.estimateNote'  => ['fr' => 'Estimation à titre indicatif — notre équipe confirmera la disponibilité et le montant sous 24h.', 'en' => 'This estimate is indicative — our team will confirm availability and the final amount within 24h.', 'de' => 'Diese Schätzung ist unverbindlich — unser Team bestätigt Verfügbarkeit und Endbetrag innerhalb von 24 Std.', 'pl' => 'Wycena ma charakter orientacyjny — nasz zespół potwierdzi dostępność i ostateczną kwotę w ciągu 24h.', 'ru' => 'Расчёт носит ориентировочный характер — наша команда подтвердит наличие мест и точную сумму в течение 24 часов.'],
            'ui.pickDates'     => ['fr' => 'Choisissez vos dates pour voir l’estimation.', 'en' => 'Choose your dates to see the estimate.', 'de' => 'Wählen Sie Ihre Reisedaten, um die Schätzung zu sehen.', 'pl' => 'Wybierz daty pobytu, aby zobaczyć wycenę.', 'ru' => 'Выберите даты пребывания, чтобы увидеть расчёт.'],
            'ui.maxRoomsHit'   => ['fr' => 'Maximum de chambres atteint', 'en' => 'Maximum number of rooms reached', 'de' => 'Maximale Zimmeranzahl erreicht', 'pl' => 'Osiągnięto maksymalną liczbę pokoi', 'ru' => 'Достигнуто максимальное количество номеров'],
            'ui.yourRooms'     => ['fr' => 'Vos chambres', 'en' => 'Your rooms', 'de' => 'Ihre Zimmer', 'pl' => 'Twoje pokoje', 'ru' => 'Ваши номера'],

            // Popup heading/sub-heading. These are injected as CSS `content:`
            // on #popmake-3241 (see villa-azur-fix.php) because the popup's own
            // content field is managed by Popup Maker — so they need to be
            // available to PHP at wp_head time, not just to the JS bundle.
            'popup.title'    => ['fr' => 'Réservez votre séjour', 'en' => 'Book your stay', 'de' => 'Buchen Sie Ihren Aufenthalt', 'pl' => 'Zarezerwuj swój pobyt', 'ru' => 'Забронируйте своё пребывание'],
            'popup.subtitle' => ['fr' => 'Villa Azur Djerba — réponse sous 24h', 'en' => 'Villa Azur Djerba — reply within 24h', 'de' => 'Villa Azur Djerba — Antwort innerhalb von 24 Std.', 'pl' => 'Villa Azur Djerba — odpowiedź w ciągu 24h', 'ru' => 'Villa Azur Djerba — ответ в течение 24 часов'],
            'ui.stay'          => ['fr' => 'Séjour', 'en' => 'Stay', 'de' => 'Aufenthalt', 'pl' => 'Pobyt', 'ru' => 'Срок пребывания'],

            // ── Room types / boards / discounts (used both in config() labels
            //    sent to the browser, and in server-generated text/emails) ────
            'room_type.simple.label' => ['fr' => 'Chambre Simple', 'en' => 'Single Room', 'de' => 'Einzelzimmer', 'pl' => 'Pokój jednoosobowy', 'ru' => 'Одноместный номер'],
            'room_type.simple.sub'   => ['fr' => 'Vue mer · idéale 1 personne', 'en' => 'Sea view · ideal for 1 person', 'de' => 'Meerblick · ideal für 1 Person', 'pl' => 'Widok na morze · idealny dla 1 osoby', 'ru' => 'Вид на море · идеально для 1 человека'],
            'room_type.double.label' => ['fr' => 'Chambre Double', 'en' => 'Double Room', 'de' => 'Doppelzimmer', 'pl' => 'Pokój dwuosobowy', 'ru' => 'Двухместный номер'],
            'room_type.double.sub'   => ['fr' => 'Vue mer · idéale 2 personnes', 'en' => 'Sea view · ideal for 2 people', 'de' => 'Meerblick · ideal für 2 Personen', 'pl' => 'Widok na morze · idealny dla 2 osób', 'ru' => 'Вид на море · идеально для 2 человек'],

            'board.bb.label' => ['fr' => 'Petit-déjeuner', 'en' => 'Breakfast', 'de' => 'Frühstück', 'pl' => 'Śniadanie', 'ru' => 'Завтрак'],
            'board.bb.sub'   => ['fr' => 'Logement + petit déjeuner', 'en' => 'Room + breakfast', 'de' => 'Übernachtung + Frühstück', 'pl' => 'Nocleg + śniadanie', 'ru' => 'Проживание + завтрак'],
            'board.hb.label' => ['fr' => 'Demi-pension', 'en' => 'Half board', 'de' => 'Halbpension', 'pl' => 'Śniadanie i kolacja', 'ru' => 'Полупансион'],
            'board.hb.sub'   => ['fr' => 'Petit-déjeuner + dîner', 'en' => 'Breakfast + dinner', 'de' => 'Frühstück + Abendessen', 'pl' => 'Śniadanie + kolacja', 'ru' => 'Завтрак + ужин'],

            'discount.child_under_12.label' => ['fr' => 'Réduction enfant (-12 ans)', 'en' => 'Child discount (under 12)', 'de' => 'Kinderermäßigung (unter 12)', 'pl' => 'Zniżka dla dziecka (do 12 lat)', 'ru' => 'Скидка для ребёнка (до 12 лет)'],
            'discount.third_adult.label'     => ['fr' => '3ᵉ adulte', 'en' => '3rd adult', 'de' => '3. Erwachsener', 'pl' => '3. dorosły', 'ru' => '3-й взрослый'],

            'tourist_tax.label' => ['fr' => 'Taxe de séjour', 'en' => 'Tourist tax', 'de' => 'Kurtaxe', 'pl' => 'Opłata turystyczna', 'ru' => 'Туристический сбор'],

            // ── Validation messages ──────────────────────────────────────────
            'val.datesInvalid'   => ['fr' => "La date de départ doit être postérieure à la date d'arrivée (au moins une nuit).", 'en' => 'The check-out date must be after the check-in date (at least one night).', 'de' => 'Das Abreisedatum muss nach dem Anreisedatum liegen (mindestens eine Nacht).', 'pl' => 'Data wyjazdu musi być późniejsza niż data przyjazdu (co najmniej jedna noc).', 'ru' => 'Дата выезда должна быть позже даты заезда (минимум одна ночь).'],
            'val.maxNights'      => ['fr' => 'Un séjour ne peut excéder %d nuits par demande. Contactez-nous pour un long séjour.', 'en' => 'A stay cannot exceed %d nights per request. Please contact us for a longer stay.', 'de' => 'Ein Aufenthalt darf pro Anfrage %d Nächte nicht überschreiten. Bitte kontaktieren Sie uns für einen längeren Aufenthalt.', 'pl' => 'Pobyt nie może przekraczać %d nocy w ramach jednego zapytania. W przypadku dłuższego pobytu prosimy o kontakt.', 'ru' => 'Продолжительность пребывания не может превышать %d ночей за один запрос. Для более длительного пребывания свяжитесь с нами.'],
            'val.noRooms'        => ['fr' => 'Veuillez configurer au moins une chambre.', 'en' => 'Please configure at least one room.', 'de' => 'Bitte konfigurieren Sie mindestens ein Zimmer.', 'pl' => 'Proszę skonfigurować co najmniej jeden pokój.', 'ru' => 'Пожалуйста, укажите хотя бы один номер.'],
            'val.maxRooms'       => ['fr' => 'Maximum %d chambres par réservation.', 'en' => 'Maximum %d rooms per reservation.', 'de' => 'Maximal %d Zimmer pro Reservierung.', 'pl' => 'Maksymalnie %d pokoi na jedną rezerwację.', 'ru' => 'Максимум %d номеров на одно бронирование.'],
            'val.minAdult'       => ['fr' => '%s : au moins un adulte est requis.', 'en' => '%s: at least one adult is required.', 'de' => '%s: mindestens ein Erwachsener ist erforderlich.', 'pl' => '%s: wymagany jest co najmniej jeden dorosły.', 'ru' => '%s: требуется как минимум один взрослый.'],
            'val.maxAdults'      => ['fr' => '%s (%s) : maximum %d %s.', 'en' => '%s (%s): maximum %d %s.', 'de' => '%s (%s): maximal %d %s.', 'pl' => '%s (%s): maksymalnie %d %s.', 'ru' => '%s (%s): максимум %d %s.'],
            'val.maxChildren'    => ['fr' => '%s (%s) : maximum %d %s.', 'en' => '%s (%s): maximum %d %s.', 'de' => '%s (%s): maximal %d %s.', 'pl' => '%s (%s): maksymalnie %d %s.', 'ru' => '%s (%s): максимум %d %s.'],
            'val.maxOccupants'   => ['fr' => '%s (%s) : maximum %d %s au total.', 'en' => '%s (%s): maximum %d %s in total.', 'de' => '%s (%s): maximal %d %s insgesamt.', 'pl' => '%s (%s): maksymalnie %d %s łącznie.', 'ru' => '%s (%s): максимум %d %s всего.'],
            'val.missingConfig'  => ['fr' => 'Configuration des chambres manquante. Merci de réessayer.', 'en' => 'Room configuration missing. Please try again.', 'de' => 'Zimmerkonfiguration fehlt. Bitte versuchen Sie es erneut.', 'pl' => 'Brak konfiguracji pokoi. Proszę spróbować ponownie.', 'ru' => 'Отсутствует конфигурация номеров. Пожалуйста, попробуйте снова.'],

            // ── Client confirmation email ────────────────────────────────────
            'email.client.subject' => ['fr' => 'Villa Azur — Votre demande de réservation est bien reçue', 'en' => 'Villa Azur — Your reservation request has been received', 'de' => 'Villa Azur — Ihre Reservierungsanfrage ist eingegangen', 'pl' => 'Villa Azur — Twoje zapytanie o rezerwację zostało przyjęte', 'ru' => 'Villa Azur — Ваш запрос на бронирование получен'],
            'email.client.heading'  => ['fr' => 'Merci, %s !', 'en' => 'Thank you, %s!', 'de' => 'Vielen Dank, %s!', 'pl' => 'Dziękujemy, %s!', 'ru' => 'Спасибо, %s!'],
            'email.client.intro'    => ['fr' => "Nous avons bien reçu votre demande de réservation à Villa Azur Djerba, et nous nous réjouissons déjà à l'idée de vous accueillir. Notre équipe vous contactera sous 24h pour confirmer la disponibilité et finaliser votre séjour.", 'en' => 'We have received your reservation request for Villa Azur Djerba, and we are already looking forward to welcoming you. Our team will contact you within 24 hours to confirm availability and finalise your stay.', 'de' => 'Wir haben Ihre Reservierungsanfrage für die Villa Azur Djerba erhalten und freuen uns bereits darauf, Sie bei uns willkommen zu heißen. Unser Team wird sich innerhalb von 24 Stunden bei Ihnen melden, um die Verfügbarkeit zu bestätigen und Ihren Aufenthalt zu finalisieren.', 'pl' => 'Otrzymaliśmy Państwa zapytanie o rezerwację w Villa Azur Djerba i już nie możemy się doczekać, aby Państwa gościć. Nasz zespół skontaktuje się w ciągu 24 godzin, aby potwierdzić dostępność i sfinalizować szczegóły pobytu.', 'ru' => 'Мы получили ваш запрос на бронирование в Villa Azur Djerba и уже рады возможности принять вас у себя. Наша команда свяжется с вами в течение 24 часов, чтобы подтвердить наличие мест и завершить оформление вашего пребывания.'],
            'email.client.footer'   => ['fr' => 'Villa Azur Djerba — Plage de Sidi Mehrez<br>Tél / WhatsApp : +216 75 757 257 &middot; villa_azur@yahoo.fr', 'en' => 'Villa Azur Djerba — Sidi Mehrez Beach<br>Phone / WhatsApp: +216 75 757 257 &middot; villa_azur@yahoo.fr', 'de' => 'Villa Azur Djerba — Strand von Sidi Mehrez<br>Tel. / WhatsApp: +216 75 757 257 &middot; villa_azur@yahoo.fr', 'pl' => 'Villa Azur Djerba — Plaża Sidi Mehrez<br>Tel. / WhatsApp: +216 75 757 257 &middot; villa_azur@yahoo.fr', 'ru' => 'Villa Azur Djerba — Пляж Сиди-Мехрез<br>Тел. / WhatsApp: +216 75 757 257 &middot; villa_azur@yahoo.fr'],

            // ── Welcome block (email_welcome_html) ───────────────────────────
            'email.welcome.p1' => ['fr' => "Villa Azur est bien plus qu'un hôtel : c'est une maison de famille où l'hospitalité est une tradition. Avec seulement 16 chambres ouvertes sur la Méditerranée, nous vous préparons un accueil intime et chaleureux, à l'image de l'art de vivre djerbien — là où la mer rencontre la sérénité.", 'en' => 'Villa Azur is far more than a hotel: it is a family home where hospitality is a tradition. With only 16 rooms open to the Mediterranean, we are preparing an intimate, warm welcome for you, true to the Djerbian art of living — where the sea meets serenity.', 'de' => 'Villa Azur ist weit mehr als ein Hotel: Es ist ein Familienhaus, in dem Gastfreundschaft Tradition hat. Mit nur 16 Zimmern zum Mittelmeer bereiten wir Ihnen einen persönlichen, herzlichen Empfang, ganz im Sinne der djerbischen Lebenskunst — dort, wo das Meer auf Gelassenheit trifft.', 'pl' => 'Villa Azur to znacznie więcej niż hotel: to rodzinny dom, w którym gościnność jest tradycją. Mając zaledwie 16 pokoi otwartych na Morze Śródziemne, przygotowujemy dla Państwa kameralne i ciepłe przyjęcie, w duchu dżerbańskiej sztuki życia — tam, gdzie morze spotyka się ze spokojem.', 'ru' => 'Villa Azur — это гораздо больше, чем отель: это семейный дом, где гостеприимство является традицией. Имея всего 16 номеров с видом на Средиземное море, мы готовим для вас тёплый, душевный приём в духе джербийского искусства жить — там, где море встречается со спокойствием.'],
            'email.welcome.p2' => ['fr' => "Toute l'équipe se réjouit déjà à l'idée de vous accueillir sur la plage de Sidi Mehrez. En attendant notre confirmation sous 24h, n'hésitez pas à nous écrire si la moindre question se présente — nous sommes là pour que votre séjour commence dans les meilleures conditions, avant même votre arrivée.", 'en' => 'Our whole team is already looking forward to welcoming you on Sidi Mehrez beach. While you wait for our confirmation within 24 hours, please do not hesitate to write to us with any question at all — we are here to make sure your stay starts under the best conditions, even before you arrive.', 'de' => 'Unser gesamtes Team freut sich bereits darauf, Sie am Strand von Sidi Mehrez willkommen zu heißen. Während Sie auf unsere Bestätigung innerhalb von 24 Stunden warten, zögern Sie bitte nicht, uns bei der kleinsten Frage zu schreiben — wir sind für Sie da, damit Ihr Aufenthalt schon vor Ihrer Ankunft unter den besten Voraussetzungen beginnt.', 'pl' => 'Cały nasz zespół z niecierpliwością czeka, aby powitać Państwa na plaży Sidi Mehrez. Oczekując na nasze potwierdzenie w ciągu 24 godzin, prosimy śmiało pisać do nas z każdym, nawet najmniejszym pytaniem — jesteśmy tu po to, aby Państwa pobyt rozpoczął się w jak najlepszych warunkach, jeszcze przed przyjazdem.', 'ru' => 'Вся наша команда уже с нетерпением ждёт возможности принять вас на пляже Сиди-Мехрез. Пока вы ожидаете нашего подтверждения в течение 24 часов, пожалуйста, не стесняйтесь писать нам по любому вопросу — мы здесь для того, чтобы ваше пребывание началось на самых лучших условиях ещё до вашего приезда.'],
            'email.welcome.sig' => ['fr' => "— L'équipe Villa Azur, Djerba", 'en' => '— The Villa Azur team, Djerba', 'de' => '— Das Villa-Azur-Team, Djerba', 'pl' => '— Zespół Villa Azur, Dżerba', 'ru' => '— Команда Villa Azur, Джерба'],

            // ── Contact recap block (email_contact_recap_html) ──────────────
            'recap.heading'    => ['fr' => 'Coordonnées', 'en' => 'Contact details', 'de' => 'Kontaktdaten', 'pl' => 'Dane kontaktowe', 'ru' => 'Контактные данные'],
            'recap.name'       => ['fr' => 'Nom', 'en' => 'Name', 'de' => 'Name', 'pl' => 'Imię i nazwisko', 'ru' => 'Имя'],
            'recap.email'      => ['fr' => 'Email', 'en' => 'Email', 'de' => 'E-Mail', 'pl' => 'E-mail', 'ru' => 'Email'],
            'recap.phone'      => ['fr' => 'Téléphone / WhatsApp', 'en' => 'Phone / WhatsApp', 'de' => 'Telefon / WhatsApp', 'pl' => 'Telefon / WhatsApp', 'ru' => 'Телефон / WhatsApp'],
            'recap.stay'       => ['fr' => 'Séjour souhaité', 'en' => 'Requested stay', 'de' => 'Gewünschter Aufenthalt', 'pl' => 'Preferowany pobyt', 'ru' => 'Желаемые даты пребывания'],
            'recap.request'    => ['fr' => 'Demande particulière / occasion', 'en' => 'Special request / occasion', 'de' => 'Besonderer Wunsch / Anlass', 'pl' => 'Specjalna prośba / okazja', 'ru' => 'Особые пожелания / повод'],

            // ── Email details block (email_details_html) ────────────────────
            'details.touristTaxNote'  => ['fr' => '&#9432; Taxe de séjour : %d %s par personne et par nuit, plafonnée à %d %s (taxe gouvernementale, Loi de finances 2024).', 'en' => '&#9432; Tourist tax: %d %s per person, per night, capped at %d %s (government tax, 2024 Finance Act).', 'de' => '&#9432; Kurtaxe: %d %s pro Person und Nacht, begrenzt auf %d %s (staatliche Abgabe, Finanzgesetz 2024).', 'pl' => '&#9432; Opłata turystyczna: %d %s za osobę za dobę, maksymalnie za %d %s (opłata państwowa, Ustawa budżetowa 2024).', 'ru' => '&#9432; Туристический сбор: %d %s с человека за ночь, не более чем за %d %s (государственный сбор, Закон о финансах 2024).'],
            'details.stayTotal'       => ['fr' => 'Séjour estimé à', 'en' => 'Estimated stay total', 'de' => 'Geschätzter Gesamtpreis', 'pl' => 'Szacowana kwota pobytu', 'ru' => 'Ориентировочная стоимость проживания'],
            'details.bottomNote'      => ['fr' => 'Estimation à titre indicatif — notre équipe confirmera la disponibilité et le montant définitif sous 24h.', 'en' => 'This is an indicative estimate — our team will confirm availability and the final amount within 24h.', 'de' => 'Dies ist eine unverbindliche Schätzung — unser Team bestätigt Verfügbarkeit und den endgültigen Betrag innerhalb von 24 Stunden.', 'pl' => 'To wycena orientacyjna — nasz zespół potwierdzi dostępność i ostateczną kwotę w ciągu 24 godzin.', 'ru' => 'Это ориентировочный расчёт — наша команда подтвердит наличие мест и итоговую сумму в течение 24 часов.'],
            'details.singleSuppNote' => ['fr' => 'Supplément single &middot; +%s %s', 'en' => 'Single occupancy supplement &middot; +%s %s', 'de' => 'Einzelzimmerzuschlag &middot; +%s %s', 'pl' => 'Dopłata za pokój jednoosobowy &middot; +%s %s', 'ru' => 'Доплата за одноместное размещение &middot; +%s %s'],

            // ── Plain-text summary/breakdown (entries list, non-HTML) ───────
            'plain.totalEstimated' => ['fr' => 'TOTAL ESTIMÉ', 'en' => 'ESTIMATED TOTAL', 'de' => 'GESCHÄTZTER GESAMTPREIS', 'pl' => 'SZACOWANA SUMA', 'ru' => 'ИТОГО (РАСЧЁТНО)'],

            // ── Form 4 (reservation) field labels/placeholders — Fluent Forms
            //    has no Polylang integration, so these are localized via the
            //    fluentform/rendering_field_data_* filters (see vaz-form-labels-i18n.php).
            'f4.first_name.label'       => ['fr' => 'Prénom', 'en' => 'First name', 'de' => 'Vorname', 'pl' => 'Imię', 'ru' => 'Имя'],
            'f4.first_name.placeholder' => ['fr' => 'Votre Prénom', 'en' => 'Your first name', 'de' => 'Ihr Vorname', 'pl' => 'Twoje imię', 'ru' => 'Ваше имя'],
            'f4.last_name.label'        => ['fr' => 'Nom', 'en' => 'Last name', 'de' => 'Nachname', 'pl' => 'Nazwisko', 'ru' => 'Фамилия'],
            'f4.last_name.placeholder'  => ['fr' => 'Votre Nom', 'en' => 'Your last name', 'de' => 'Ihr Nachname', 'pl' => 'Twoje nazwisko', 'ru' => 'Ваша фамилия'],
            'f4.phone.label'            => ['fr' => 'Téléphone ou WhatsApp', 'en' => 'Phone or WhatsApp', 'de' => 'Telefon oder WhatsApp', 'pl' => 'Telefon lub WhatsApp', 'ru' => 'Телефон или WhatsApp'],
            'f4.phone.placeholder'      => ['fr' => 'XX XXX XXX', 'en' => 'e.g. +44 7000 000000', 'de' => 'z. B. +49 170 0000000', 'pl' => 'np. +48 600 000 000', 'ru' => 'напр. +7 900 000 00 00'],
            'f4.email.label'            => ['fr' => 'Email', 'en' => 'Email', 'de' => 'E-Mail', 'pl' => 'E-mail', 'ru' => 'Email'],
            'f4.email.placeholder'      => ['fr' => 'votre@email.com', 'en' => 'your@email.com', 'de' => 'ihre@email.com', 'pl' => 'twoj@email.com', 'ru' => 'your@email.com'],
            'f4.checkin.label'          => ['fr' => "Date d'arrivée", 'en' => 'Check-in date', 'de' => 'Anreisedatum', 'pl' => 'Data przyjazdu', 'ru' => 'Дата заезда'],
            'f4.checkout.label'         => ['fr' => 'Date de départ', 'en' => 'Check-out date', 'de' => 'Abreisedatum', 'pl' => 'Data wyjazdu', 'ru' => 'Дата выезда'],
            'f4.date.placeholder'       => ['fr' => 'jj/mm/aaaa', 'en' => 'dd/mm/yyyy', 'de' => 'tt.mm.jjjj', 'pl' => 'dd/mm/rrrr', 'ru' => 'дд/мм/гггг'],
            'f4.request.label'          => ['fr' => 'Demande particulière ou occasion', 'en' => 'Special request or occasion', 'de' => 'Besonderer Wunsch oder Anlass', 'pl' => 'Specjalna prośba lub okazja', 'ru' => 'Особые пожелания или повод'],
            'f4.request.placeholder'    => ['fr' => "Occasion spéciale (facultatif) : anniversaire, lune de miel, besoins d'accessibilité, allergies, informations d'arrivée, ou toute autre demande.", 'en' => 'Special occasion (optional): anniversary, honeymoon, accessibility needs, allergies, arrival details, or any other request.', 'de' => 'Besonderer Anlass (optional): Jahrestag, Flitterwochen, besondere Bedürfnisse, Allergien, Ankunftsdetails oder jeder andere Wunsch.', 'pl' => 'Specjalna okazja (opcjonalnie): rocznica, podróż poślubna, potrzeby związane z dostępnością, alergie, informacje o przyjeździe lub inna prośba.', 'ru' => 'Особый повод (необязательно): годовщина, медовый месяц, особые потребности, аллергии, информация о прибытии или другая просьба.'],
            'f4.submit'                 => ['fr' => 'Envoyer la demande', 'en' => 'Send request', 'de' => 'Anfrage senden', 'pl' => 'Wyślij zapytanie', 'ru' => 'Отправить запрос'],

            // ── Form 3 (contact) field labels/placeholders + notification ───
            'f3.name.label'          => ['fr' => 'Nom complet', 'en' => 'Full name', 'de' => 'Vollständiger Name', 'pl' => 'Imię i nazwisko', 'ru' => 'Полное имя'],
            'f3.name.placeholder'    => ['fr' => 'Votre nom complet', 'en' => 'Your full name', 'de' => 'Ihr vollständiger Name', 'pl' => 'Twoje imię i nazwisko', 'ru' => 'Ваше полное имя'],
            'f3.email.label'         => ['fr' => 'Adresse email', 'en' => 'Email address', 'de' => 'E-Mail-Adresse', 'pl' => 'Adres e-mail', 'ru' => 'Адрес электронной почты'],
            'f3.email.placeholder'   => ['fr' => 'votre@email.com', 'en' => 'your@email.com', 'de' => 'ihre@email.com', 'pl' => 'twoj@email.com', 'ru' => 'your@email.com'],
            'f3.phone.label'         => ['fr' => 'Téléphone', 'en' => 'Phone number', 'de' => 'Telefonnummer', 'pl' => 'Numer telefonu', 'ru' => 'Номер телефона'],
            'f3.phone.placeholder'   => ['fr' => '+216 XX XXX XXX', 'en' => 'e.g. +44 7000 000000', 'de' => 'z. B. +49 170 0000000', 'pl' => 'np. +48 600 000 000', 'ru' => 'напр. +7 900 000 00 00'],
            'f3.type.label'          => ['fr' => 'Type de demande', 'en' => 'Request type', 'de' => 'Art der Anfrage', 'pl' => 'Rodzaj zapytania', 'ru' => 'Тип запроса'],
            'f3.message.label'       => ['fr' => 'Message', 'en' => 'Message', 'de' => 'Nachricht', 'pl' => 'Wiadomość', 'ru' => 'Сообщение'],
            'f3.message.placeholder' => ['fr' => 'Votre message...', 'en' => 'Your message...', 'de' => 'Ihre Nachricht...', 'pl' => 'Twoja wiadomość...', 'ru' => 'Ваше сообщение...'],
            'f3.submit'              => ['fr' => 'Envoyer le message', 'en' => 'Send message', 'de' => 'Nachricht senden', 'pl' => 'Wyślij wiadomość', 'ru' => 'Отправить сообщение'],

            'f3.subject' => ['fr' => 'Villa Azur — Nous avons bien reçu votre message', 'en' => 'Villa Azur — We have received your message', 'de' => 'Villa Azur — Wir haben Ihre Nachricht erhalten', 'pl' => 'Villa Azur — Otrzymaliśmy Twoją wiadomość', 'ru' => 'Villa Azur — Мы получили ваше сообщение'],
            'f3.intro'   => ['fr' => 'Nous avons bien reçu votre message et nous vous répondrons dans les meilleurs délais. Voici un récapitulatif de votre demande :', 'en' => 'We have received your message and will get back to you as soon as possible. Here is a summary of your request:', 'de' => 'Wir haben Ihre Nachricht erhalten und werden uns so schnell wie möglich bei Ihnen melden. Hier eine Zusammenfassung Ihrer Anfrage:', 'pl' => 'Otrzymaliśmy Twoją wiadomość i odpowiemy najszybciej, jak to możliwe. Oto podsumowanie Twojego zapytania:', 'ru' => 'Мы получили ваше сообщение и ответим вам в кратчайшие сроки. Ниже приведена сводка вашего запроса:'],

            // Select options for form 3's "type_de_demande" field, keyed by the
            // field's stored VALUE (never translated — only the label shown).
            'f3.type.opt.information'               => ['fr' => "Demande d'information générale", 'en' => 'General information request', 'de' => 'Allgemeine Informationsanfrage', 'pl' => 'Ogólne zapytanie informacyjne', 'ru' => 'Общий информационный запрос'],
            'f3.type.opt.reservation'                => ['fr' => 'Demande de réservation', 'en' => 'Reservation request', 'de' => 'Reservierungsanfrage', 'pl' => 'Zapytanie o rezerwację', 'ru' => 'Запрос на бронирование'],
            'f3.type.opt.annulation_modification'    => ['fr' => 'Annulation ou modification de réservation', 'en' => 'Cancel or change a reservation', 'de' => 'Stornierung oder Änderung einer Reservierung', 'pl' => 'Anulowanie lub zmiana rezerwacji', 'ru' => 'Отмена или изменение бронирования'],
            'f3.type.opt.evenement_prive'            => ['fr' => 'Événement privé (mariage, anniversaire, séminaire)', 'en' => 'Private event (wedding, birthday, seminar)', 'de' => 'Private Veranstaltung (Hochzeit, Geburtstag, Seminar)', 'pl' => 'Wydarzenie prywatne (ślub, urodziny, seminarium)', 'ru' => 'Частное мероприятие (свадьба, день рождения, семинар)'],
            'f3.type.opt.devis_groupe'               => ['fr' => 'Demande de devis groupe', 'en' => 'Group quote request', 'de' => 'Anfrage für Gruppenangebot', 'pl' => 'Zapytanie o wycenę grupową', 'ru' => 'Запрос группового расчёта'],
            'f3.type.opt.reclamation'                => ['fr' => 'Réclamation', 'en' => 'Complaint', 'de' => 'Beschwerde', 'pl' => 'Reklamacja', 'ru' => 'Жалоба'],
            'f3.type.opt.suggestion'                 => ['fr' => 'Suggestion', 'en' => 'Suggestion', 'de' => 'Vorschlag', 'pl' => 'Sugestia', 'ru' => 'Предложение'],
            'f3.type.opt.partenariat'                => ['fr' => 'Partenariat et B2B', 'en' => 'Partnership & B2B', 'de' => 'Partnerschaft & B2B', 'pl' => 'Partnerstwo i B2B', 'ru' => 'Партнёрство и B2B'],
            'f3.type.opt.presse_medias'              => ['fr' => 'Presse et médias', 'en' => 'Press & media', 'de' => 'Presse & Medien', 'pl' => 'Prasa i media', 'ru' => 'Пресса и СМИ'],
            'f3.type.opt.autre'                      => ['fr' => 'Autre', 'en' => 'Other', 'de' => 'Sonstiges', 'pl' => 'Inne', 'ru' => 'Другое'],
        ];

        return $t;
    }
}
